// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	taskdomain "github.com/10Narratives/faas/internal/domains/tasks"
)

// TaskService is an autogenerated mock type for the TaskService type
type TaskService struct {
	mock.Mock
}

type TaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskService) EXPECT() *TaskService_Expecter {
	return &TaskService_Expecter{mock: &_m.Mock}
}

// CancelTask provides a mock function with given fields: ctx, args
func (_m *TaskService) CancelTask(ctx context.Context, args *taskdomain.CancelTaskArgs) (*taskdomain.CancelTaskResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CancelTask")
	}

	var r0 *taskdomain.CancelTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.CancelTaskArgs) (*taskdomain.CancelTaskResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.CancelTaskArgs) *taskdomain.CancelTaskResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskdomain.CancelTaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *taskdomain.CancelTaskArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_CancelTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTask'
type TaskService_CancelTask_Call struct {
	*mock.Call
}

// CancelTask is a helper method to define mock.On call
//   - ctx context.Context
//   - args *taskdomain.CancelTaskArgs
func (_e *TaskService_Expecter) CancelTask(ctx interface{}, args interface{}) *TaskService_CancelTask_Call {
	return &TaskService_CancelTask_Call{Call: _e.mock.On("CancelTask", ctx, args)}
}

func (_c *TaskService_CancelTask_Call) Run(run func(ctx context.Context, args *taskdomain.CancelTaskArgs)) *TaskService_CancelTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.CancelTaskArgs))
	})
	return _c
}

func (_c *TaskService_CancelTask_Call) Return(_a0 *taskdomain.CancelTaskResult, _a1 error) *TaskService_CancelTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_CancelTask_Call) RunAndReturn(run func(context.Context, *taskdomain.CancelTaskArgs) (*taskdomain.CancelTaskResult, error)) *TaskService_CancelTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: ctx, args
func (_m *TaskService) DeleteTask(ctx context.Context, args *taskdomain.DeleteTaskArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.DeleteTaskArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskService_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type TaskService_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - args *taskdomain.DeleteTaskArgs
func (_e *TaskService_Expecter) DeleteTask(ctx interface{}, args interface{}) *TaskService_DeleteTask_Call {
	return &TaskService_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, args)}
}

func (_c *TaskService_DeleteTask_Call) Run(run func(ctx context.Context, args *taskdomain.DeleteTaskArgs)) *TaskService_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.DeleteTaskArgs))
	})
	return _c
}

func (_c *TaskService_DeleteTask_Call) Return(_a0 error) *TaskService_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskService_DeleteTask_Call) RunAndReturn(run func(context.Context, *taskdomain.DeleteTaskArgs) error) *TaskService_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, args
func (_m *TaskService) GetTask(ctx context.Context, args *taskdomain.GetTaskArgs) (*taskdomain.GetTaskResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *taskdomain.GetTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.GetTaskArgs) (*taskdomain.GetTaskResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.GetTaskArgs) *taskdomain.GetTaskResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskdomain.GetTaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *taskdomain.GetTaskArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type TaskService_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - args *taskdomain.GetTaskArgs
func (_e *TaskService_Expecter) GetTask(ctx interface{}, args interface{}) *TaskService_GetTask_Call {
	return &TaskService_GetTask_Call{Call: _e.mock.On("GetTask", ctx, args)}
}

func (_c *TaskService_GetTask_Call) Run(run func(ctx context.Context, args *taskdomain.GetTaskArgs)) *TaskService_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.GetTaskArgs))
	})
	return _c
}

func (_c *TaskService_GetTask_Call) Return(_a0 *taskdomain.GetTaskResult, _a1 error) *TaskService_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_GetTask_Call) RunAndReturn(run func(context.Context, *taskdomain.GetTaskArgs) (*taskdomain.GetTaskResult, error)) *TaskService_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx, args
func (_m *TaskService) ListTasks(ctx context.Context, args *taskdomain.ListTasksArgs) (*taskdomain.ListTaskResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 *taskdomain.ListTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.ListTasksArgs) (*taskdomain.ListTaskResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.ListTasksArgs) *taskdomain.ListTaskResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskdomain.ListTaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *taskdomain.ListTasksArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type TaskService_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - args *taskdomain.ListTasksArgs
func (_e *TaskService_Expecter) ListTasks(ctx interface{}, args interface{}) *TaskService_ListTasks_Call {
	return &TaskService_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, args)}
}

func (_c *TaskService_ListTasks_Call) Run(run func(ctx context.Context, args *taskdomain.ListTasksArgs)) *TaskService_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.ListTasksArgs))
	})
	return _c
}

func (_c *TaskService_ListTasks_Call) Return(_a0 *taskdomain.ListTaskResult, _a1 error) *TaskService_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_ListTasks_Call) RunAndReturn(run func(context.Context, *taskdomain.ListTasksArgs) (*taskdomain.ListTaskResult, error)) *TaskService_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskService creates a new instance of TaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskService {
	mock := &TaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
