// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/10Narratives/faas/internal/domain/operations"
	mock "github.com/stretchr/testify/mock"
)

// NewOperationService creates a new instance of OperationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperationService {
	mock := &OperationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OperationService is an autogenerated mock type for the OperationService type
type OperationService struct {
	mock.Mock
}

type OperationService_Expecter struct {
	mock *mock.Mock
}

func (_m *OperationService) EXPECT() *OperationService_Expecter {
	return &OperationService_Expecter{mock: &_m.Mock}
}

// CancelOperation provides a mock function for the type OperationService
func (_mock *OperationService) CancelOperation(ctx context.Context, opts *opdomain.CancelOperationOptions) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CancelOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opdomain.CancelOperationOptions) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OperationService_CancelOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOperation'
type OperationService_CancelOperation_Call struct {
	*mock.Call
}

// CancelOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *opdomain.CancelOperationOptions
func (_e *OperationService_Expecter) CancelOperation(ctx interface{}, opts interface{}) *OperationService_CancelOperation_Call {
	return &OperationService_CancelOperation_Call{Call: _e.mock.On("CancelOperation", ctx, opts)}
}

func (_c *OperationService_CancelOperation_Call) Run(run func(ctx context.Context, opts *opdomain.CancelOperationOptions)) *OperationService_CancelOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opdomain.CancelOperationOptions
		if args[1] != nil {
			arg1 = args[1].(*opdomain.CancelOperationOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OperationService_CancelOperation_Call) Return(err error) *OperationService_CancelOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OperationService_CancelOperation_Call) RunAndReturn(run func(ctx context.Context, opts *opdomain.CancelOperationOptions) error) *OperationService_CancelOperation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOperation provides a mock function for the type OperationService
func (_mock *OperationService) DeleteOperation(ctx context.Context, opts *opdomain.DeleteOperationOptions) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opdomain.DeleteOperationOptions) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OperationService_DeleteOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOperation'
type OperationService_DeleteOperation_Call struct {
	*mock.Call
}

// DeleteOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *opdomain.DeleteOperationOptions
func (_e *OperationService_Expecter) DeleteOperation(ctx interface{}, opts interface{}) *OperationService_DeleteOperation_Call {
	return &OperationService_DeleteOperation_Call{Call: _e.mock.On("DeleteOperation", ctx, opts)}
}

func (_c *OperationService_DeleteOperation_Call) Run(run func(ctx context.Context, opts *opdomain.DeleteOperationOptions)) *OperationService_DeleteOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opdomain.DeleteOperationOptions
		if args[1] != nil {
			arg1 = args[1].(*opdomain.DeleteOperationOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OperationService_DeleteOperation_Call) Return(err error) *OperationService_DeleteOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OperationService_DeleteOperation_Call) RunAndReturn(run func(ctx context.Context, opts *opdomain.DeleteOperationOptions) error) *OperationService_DeleteOperation_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperation provides a mock function for the type OperationService
func (_mock *OperationService) GetOperation(ctx context.Context, opts *opdomain.GetOperationOptions) (*opdomain.Operation, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetOperation")
	}

	var r0 *opdomain.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opdomain.GetOperationOptions) (*opdomain.Operation, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opdomain.GetOperationOptions) *opdomain.Operation); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opdomain.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opdomain.GetOperationOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OperationService_GetOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperation'
type OperationService_GetOperation_Call struct {
	*mock.Call
}

// GetOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *opdomain.GetOperationOptions
func (_e *OperationService_Expecter) GetOperation(ctx interface{}, opts interface{}) *OperationService_GetOperation_Call {
	return &OperationService_GetOperation_Call{Call: _e.mock.On("GetOperation", ctx, opts)}
}

func (_c *OperationService_GetOperation_Call) Run(run func(ctx context.Context, opts *opdomain.GetOperationOptions)) *OperationService_GetOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opdomain.GetOperationOptions
		if args[1] != nil {
			arg1 = args[1].(*opdomain.GetOperationOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OperationService_GetOperation_Call) Return(operation *opdomain.Operation, err error) *OperationService_GetOperation_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *OperationService_GetOperation_Call) RunAndReturn(run func(ctx context.Context, opts *opdomain.GetOperationOptions) (*opdomain.Operation, error)) *OperationService_GetOperation_Call {
	_c.Call.Return(run)
	return _c
}

// ListOperations provides a mock function for the type OperationService
func (_mock *OperationService) ListOperations(ctx context.Context, opts *opdomain.ListOperationsOptions) (*opdomain.ListOperationsResult, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListOperations")
	}

	var r0 *opdomain.ListOperationsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opdomain.ListOperationsOptions) (*opdomain.ListOperationsResult, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opdomain.ListOperationsOptions) *opdomain.ListOperationsResult); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opdomain.ListOperationsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opdomain.ListOperationsOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OperationService_ListOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOperations'
type OperationService_ListOperations_Call struct {
	*mock.Call
}

// ListOperations is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *opdomain.ListOperationsOptions
func (_e *OperationService_Expecter) ListOperations(ctx interface{}, opts interface{}) *OperationService_ListOperations_Call {
	return &OperationService_ListOperations_Call{Call: _e.mock.On("ListOperations", ctx, opts)}
}

func (_c *OperationService_ListOperations_Call) Run(run func(ctx context.Context, opts *opdomain.ListOperationsOptions)) *OperationService_ListOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opdomain.ListOperationsOptions
		if args[1] != nil {
			arg1 = args[1].(*opdomain.ListOperationsOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OperationService_ListOperations_Call) Return(listOperationsResult *opdomain.ListOperationsResult, err error) *OperationService_ListOperations_Call {
	_c.Call.Return(listOperationsResult, err)
	return _c
}

func (_c *OperationService_ListOperations_Call) RunAndReturn(run func(ctx context.Context, opts *opdomain.ListOperationsOptions) (*opdomain.ListOperationsResult, error)) *OperationService_ListOperations_Call {
	_c.Call.Return(run)
	return _c
}

// WaitOperation provides a mock function for the type OperationService
func (_mock *OperationService) WaitOperation(ctx context.Context, opts *opdomain.WaitOperationOptions) (*opdomain.Operation, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for WaitOperation")
	}

	var r0 *opdomain.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opdomain.WaitOperationOptions) (*opdomain.Operation, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opdomain.WaitOperationOptions) *opdomain.Operation); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opdomain.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opdomain.WaitOperationOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OperationService_WaitOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitOperation'
type OperationService_WaitOperation_Call struct {
	*mock.Call
}

// WaitOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *opdomain.WaitOperationOptions
func (_e *OperationService_Expecter) WaitOperation(ctx interface{}, opts interface{}) *OperationService_WaitOperation_Call {
	return &OperationService_WaitOperation_Call{Call: _e.mock.On("WaitOperation", ctx, opts)}
}

func (_c *OperationService_WaitOperation_Call) Run(run func(ctx context.Context, opts *opdomain.WaitOperationOptions)) *OperationService_WaitOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opdomain.WaitOperationOptions
		if args[1] != nil {
			arg1 = args[1].(*opdomain.WaitOperationOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OperationService_WaitOperation_Call) Return(operation *opdomain.Operation, err error) *OperationService_WaitOperation_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *OperationService_WaitOperation_Call) RunAndReturn(run func(ctx context.Context, opts *opdomain.WaitOperationOptions) (*opdomain.Operation, error)) *OperationService_WaitOperation_Call {
	_c.Call.Return(run)
	return _c
}
