// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	opdomain "github.com/10Narratives/faas/internal/domains/operations"
)

// OperationService is an autogenerated mock type for the OperationService type
type OperationService struct {
	mock.Mock
}

type OperationService_Expecter struct {
	mock *mock.Mock
}

func (_m *OperationService) EXPECT() *OperationService_Expecter {
	return &OperationService_Expecter{mock: &_m.Mock}
}

// CancelOperation provides a mock function with given fields: ctx, args
func (_m *OperationService) CancelOperation(ctx context.Context, args *opdomain.CancelOperationArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CancelOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *opdomain.CancelOperationArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OperationService_CancelOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOperation'
type OperationService_CancelOperation_Call struct {
	*mock.Call
}

// CancelOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - args *opdomain.CancelOperationArgs
func (_e *OperationService_Expecter) CancelOperation(ctx interface{}, args interface{}) *OperationService_CancelOperation_Call {
	return &OperationService_CancelOperation_Call{Call: _e.mock.On("CancelOperation", ctx, args)}
}

func (_c *OperationService_CancelOperation_Call) Run(run func(ctx context.Context, args *opdomain.CancelOperationArgs)) *OperationService_CancelOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*opdomain.CancelOperationArgs))
	})
	return _c
}

func (_c *OperationService_CancelOperation_Call) Return(_a0 error) *OperationService_CancelOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OperationService_CancelOperation_Call) RunAndReturn(run func(context.Context, *opdomain.CancelOperationArgs) error) *OperationService_CancelOperation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOperation provides a mock function with given fields: ctx, args
func (_m *OperationService) DeleteOperation(ctx context.Context, args *opdomain.DeleteOperationArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *opdomain.DeleteOperationArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OperationService_DeleteOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOperation'
type OperationService_DeleteOperation_Call struct {
	*mock.Call
}

// DeleteOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - args *opdomain.DeleteOperationArgs
func (_e *OperationService_Expecter) DeleteOperation(ctx interface{}, args interface{}) *OperationService_DeleteOperation_Call {
	return &OperationService_DeleteOperation_Call{Call: _e.mock.On("DeleteOperation", ctx, args)}
}

func (_c *OperationService_DeleteOperation_Call) Run(run func(ctx context.Context, args *opdomain.DeleteOperationArgs)) *OperationService_DeleteOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*opdomain.DeleteOperationArgs))
	})
	return _c
}

func (_c *OperationService_DeleteOperation_Call) Return(_a0 error) *OperationService_DeleteOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OperationService_DeleteOperation_Call) RunAndReturn(run func(context.Context, *opdomain.DeleteOperationArgs) error) *OperationService_DeleteOperation_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperation provides a mock function with given fields: ctx, args
func (_m *OperationService) GetOperation(ctx context.Context, args *opdomain.GetOperationArgs) (*opdomain.GetOperationResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetOperation")
	}

	var r0 *opdomain.GetOperationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *opdomain.GetOperationArgs) (*opdomain.GetOperationResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *opdomain.GetOperationArgs) *opdomain.GetOperationResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opdomain.GetOperationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *opdomain.GetOperationArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OperationService_GetOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperation'
type OperationService_GetOperation_Call struct {
	*mock.Call
}

// GetOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - args *opdomain.GetOperationArgs
func (_e *OperationService_Expecter) GetOperation(ctx interface{}, args interface{}) *OperationService_GetOperation_Call {
	return &OperationService_GetOperation_Call{Call: _e.mock.On("GetOperation", ctx, args)}
}

func (_c *OperationService_GetOperation_Call) Run(run func(ctx context.Context, args *opdomain.GetOperationArgs)) *OperationService_GetOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*opdomain.GetOperationArgs))
	})
	return _c
}

func (_c *OperationService_GetOperation_Call) Return(_a0 *opdomain.GetOperationResult, _a1 error) *OperationService_GetOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OperationService_GetOperation_Call) RunAndReturn(run func(context.Context, *opdomain.GetOperationArgs) (*opdomain.GetOperationResult, error)) *OperationService_GetOperation_Call {
	_c.Call.Return(run)
	return _c
}

// ListOperations provides a mock function with given fields: ctx, args
func (_m *OperationService) ListOperations(ctx context.Context, args *opdomain.ListOperationsArgs) (*opdomain.ListOperationsResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListOperations")
	}

	var r0 *opdomain.ListOperationsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *opdomain.ListOperationsArgs) (*opdomain.ListOperationsResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *opdomain.ListOperationsArgs) *opdomain.ListOperationsResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opdomain.ListOperationsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *opdomain.ListOperationsArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OperationService_ListOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOperations'
type OperationService_ListOperations_Call struct {
	*mock.Call
}

// ListOperations is a helper method to define mock.On call
//   - ctx context.Context
//   - args *opdomain.ListOperationsArgs
func (_e *OperationService_Expecter) ListOperations(ctx interface{}, args interface{}) *OperationService_ListOperations_Call {
	return &OperationService_ListOperations_Call{Call: _e.mock.On("ListOperations", ctx, args)}
}

func (_c *OperationService_ListOperations_Call) Run(run func(ctx context.Context, args *opdomain.ListOperationsArgs)) *OperationService_ListOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*opdomain.ListOperationsArgs))
	})
	return _c
}

func (_c *OperationService_ListOperations_Call) Return(_a0 *opdomain.ListOperationsResult, _a1 error) *OperationService_ListOperations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OperationService_ListOperations_Call) RunAndReturn(run func(context.Context, *opdomain.ListOperationsArgs) (*opdomain.ListOperationsResult, error)) *OperationService_ListOperations_Call {
	_c.Call.Return(run)
	return _c
}

// WaitOperation provides a mock function with given fields: ctx, args
func (_m *OperationService) WaitOperation(ctx context.Context, args *opdomain.WaitOperationArgs) (*opdomain.WaitOperationResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for WaitOperation")
	}

	var r0 *opdomain.WaitOperationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *opdomain.WaitOperationArgs) (*opdomain.WaitOperationResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *opdomain.WaitOperationArgs) *opdomain.WaitOperationResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opdomain.WaitOperationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *opdomain.WaitOperationArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OperationService_WaitOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitOperation'
type OperationService_WaitOperation_Call struct {
	*mock.Call
}

// WaitOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - args *opdomain.WaitOperationArgs
func (_e *OperationService_Expecter) WaitOperation(ctx interface{}, args interface{}) *OperationService_WaitOperation_Call {
	return &OperationService_WaitOperation_Call{Call: _e.mock.On("WaitOperation", ctx, args)}
}

func (_c *OperationService_WaitOperation_Call) Run(run func(ctx context.Context, args *opdomain.WaitOperationArgs)) *OperationService_WaitOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*opdomain.WaitOperationArgs))
	})
	return _c
}

func (_c *OperationService_WaitOperation_Call) Return(_a0 *opdomain.WaitOperationResult, _a1 error) *OperationService_WaitOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OperationService_WaitOperation_Call) RunAndReturn(run func(context.Context, *opdomain.WaitOperationArgs) (*opdomain.WaitOperationResult, error)) *OperationService_WaitOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewOperationService creates a new instance of OperationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperationService {
	mock := &OperationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
