// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: faas/v1/functions.proto

package faaspb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFunctionMetadata_Format int32

const (
	UploadFunctionMetadata_FORMAT_UNSPECIFIED UploadFunctionMetadata_Format = 0
	UploadFunctionMetadata_FORMAT_ZIP         UploadFunctionMetadata_Format = 1
	UploadFunctionMetadata_FORMAT_TAR_GZ      UploadFunctionMetadata_Format = 2
)

// Enum value maps for UploadFunctionMetadata_Format.
var (
	UploadFunctionMetadata_Format_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_ZIP",
		2: "FORMAT_TAR_GZ",
	}
	UploadFunctionMetadata_Format_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_ZIP":         1,
		"FORMAT_TAR_GZ":      2,
	}
)

func (x UploadFunctionMetadata_Format) Enum() *UploadFunctionMetadata_Format {
	p := new(UploadFunctionMetadata_Format)
	*p = x
	return p
}

func (x UploadFunctionMetadata_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadFunctionMetadata_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_faas_v1_functions_proto_enumTypes[0].Descriptor()
}

func (UploadFunctionMetadata_Format) Type() protoreflect.EnumType {
	return &file_faas_v1_functions_proto_enumTypes[0]
}

func (x UploadFunctionMetadata_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadFunctionMetadata_Format.Descriptor instead.
func (UploadFunctionMetadata_Format) EnumDescriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{3, 0}
}

type Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	SourceBundle  *SourceBundle          `protobuf:"bytes,4,opt,name=source_bundle,json=sourceBundle,proto3" json:"source_bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_faas_v1_functions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{0}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Function) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *Function) GetSourceBundle() *SourceBundle {
	if x != nil {
		return x.SourceBundle
	}
	return nil
}

type SourceBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceBundle) Reset() {
	*x = SourceBundle{}
	mi := &file_faas_v1_functions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceBundle) ProtoMessage() {}

func (x *SourceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceBundle.ProtoReflect.Descriptor instead.
func (*SourceBundle) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{1}
}

func (x *SourceBundle) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SourceBundle) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *SourceBundle) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SourceBundle) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type UploadFunctionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadFunctionRequest_UploadFunctionMetadata
	//	*UploadFunctionRequest_UploadFunctionData
	Payload       isUploadFunctionRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFunctionRequest) Reset() {
	*x = UploadFunctionRequest{}
	mi := &file_faas_v1_functions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFunctionRequest) ProtoMessage() {}

func (x *UploadFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFunctionRequest.ProtoReflect.Descriptor instead.
func (*UploadFunctionRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFunctionRequest) GetPayload() isUploadFunctionRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadFunctionRequest) GetUploadFunctionMetadata() *UploadFunctionMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadFunctionRequest_UploadFunctionMetadata); ok {
			return x.UploadFunctionMetadata
		}
	}
	return nil
}

func (x *UploadFunctionRequest) GetUploadFunctionData() *UploadFunctionData {
	if x != nil {
		if x, ok := x.Payload.(*UploadFunctionRequest_UploadFunctionData); ok {
			return x.UploadFunctionData
		}
	}
	return nil
}

type isUploadFunctionRequest_Payload interface {
	isUploadFunctionRequest_Payload()
}

type UploadFunctionRequest_UploadFunctionMetadata struct {
	UploadFunctionMetadata *UploadFunctionMetadata `protobuf:"bytes,1,opt,name=upload_function_metadata,json=uploadFunctionMetadata,proto3,oneof"`
}

type UploadFunctionRequest_UploadFunctionData struct {
	UploadFunctionData *UploadFunctionData `protobuf:"bytes,2,opt,name=upload_function_data,json=uploadFunctionData,proto3,oneof"`
}

func (*UploadFunctionRequest_UploadFunctionMetadata) isUploadFunctionRequest_Payload() {}

func (*UploadFunctionRequest_UploadFunctionData) isUploadFunctionRequest_Payload() {}

type UploadFunctionMetadata struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	FunctionName  string                        `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Format        UploadFunctionMetadata_Format `protobuf:"varint,3,opt,name=format,proto3,enum=faas.v1.functions.UploadFunctionMetadata_Format" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFunctionMetadata) Reset() {
	*x = UploadFunctionMetadata{}
	mi := &file_faas_v1_functions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFunctionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFunctionMetadata) ProtoMessage() {}

func (x *UploadFunctionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFunctionMetadata.ProtoReflect.Descriptor instead.
func (*UploadFunctionMetadata) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{3}
}

func (x *UploadFunctionMetadata) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *UploadFunctionMetadata) GetFormat() UploadFunctionMetadata_Format {
	if x != nil {
		return x.Format
	}
	return UploadFunctionMetadata_FORMAT_UNSPECIFIED
}

type UploadFunctionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFunctionData) Reset() {
	*x = UploadFunctionData{}
	mi := &file_faas_v1_functions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFunctionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFunctionData) ProtoMessage() {}

func (x *UploadFunctionData) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFunctionData.ProtoReflect.Descriptor instead.
func (*UploadFunctionData) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{4}
}

func (x *UploadFunctionData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecuteFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parameters    string                 `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteFunctionRequest) Reset() {
	*x = ExecuteFunctionRequest{}
	mi := &file_faas_v1_functions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionRequest) ProtoMessage() {}

func (x *ExecuteFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteFunctionRequest) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

type ExecuteFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteFunctionResponse) Reset() {
	*x = ExecuteFunctionResponse{}
	mi := &file_faas_v1_functions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionResponse) ProtoMessage() {}

func (x *ExecuteFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionResponse) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteFunctionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionRequest) Reset() {
	*x = GetFunctionRequest{}
	mi := &file_faas_v1_functions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionRequest) ProtoMessage() {}

func (x *GetFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{7}
}

func (x *GetFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsRequest) Reset() {
	*x = ListFunctionsRequest{}
	mi := &file_faas_v1_functions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsRequest) ProtoMessage() {}

func (x *ListFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{8}
}

func (x *ListFunctionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFunctionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListFunctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*Function            `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsResponse) Reset() {
	*x = ListFunctionsResponse{}
	mi := &file_faas_v1_functions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsResponse) ProtoMessage() {}

func (x *ListFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{9}
}

func (x *ListFunctionsResponse) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *ListFunctionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFunctionRequest) Reset() {
	*x = DeleteFunctionRequest{}
	mi := &file_faas_v1_functions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFunctionRequest) ProtoMessage() {}

func (x *DeleteFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_functions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFunctionRequest.ProtoReflect.Descriptor instead.
func (*DeleteFunctionRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_functions_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_faas_v1_functions_proto protoreflect.FileDescriptor

const file_faas_v1_functions_proto_rawDesc = "" +
	"\n" +
	"\x17faas/v1/functions.proto\x12\x11faas.v1.functions\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xc4\x01\n" +
	"\bFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12;\n" +
	"\vuploaded_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\x12D\n" +
	"\rsource_bundle\x18\x04 \x01(\v2\x1f.faas.v1.functions.SourceBundleR\fsourceBundle\"q\n" +
	"\fSourceBundle\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"\xe4\x01\n" +
	"\x15UploadFunctionRequest\x12e\n" +
	"\x18upload_function_metadata\x18\x01 \x01(\v2).faas.v1.functions.UploadFunctionMetadataH\x00R\x16uploadFunctionMetadata\x12Y\n" +
	"\x14upload_function_data\x18\x02 \x01(\v2%.faas.v1.functions.UploadFunctionDataH\x00R\x12uploadFunctionDataB\t\n" +
	"\apayload\"\xcc\x01\n" +
	"\x16UploadFunctionMetadata\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12H\n" +
	"\x06format\x18\x03 \x01(\x0e20.faas.v1.functions.UploadFunctionMetadata.FormatR\x06format\"C\n" +
	"\x06Format\x12\x16\n" +
	"\x12FORMAT_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"FORMAT_ZIP\x10\x01\x12\x11\n" +
	"\rFORMAT_TAR_GZ\x10\x02\"(\n" +
	"\x12UploadFunctionData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"L\n" +
	"\x16ExecuteFunctionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x01(\tR\n" +
	"parameters\"-\n" +
	"\x17ExecuteFunctionResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x12GetFunctionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"R\n" +
	"\x14ListFunctionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"z\n" +
	"\x15ListFunctionsResponse\x129\n" +
	"\tfunctions\x18\x01 \x03(\v2\x1b.faas.v1.functions.FunctionR\tfunctions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"+\n" +
	"\x15DeleteFunctionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xdb\x03\n" +
	"\tFunctions\x12Y\n" +
	"\x0eUploadFunction\x12(.faas.v1.functions.UploadFunctionRequest\x1a\x1b.faas.v1.functions.Function(\x01\x12h\n" +
	"\x0fExecuteFunction\x12).faas.v1.functions.ExecuteFunctionRequest\x1a*.faas.v1.functions.ExecuteFunctionResponse\x12Q\n" +
	"\vGetFunction\x12%.faas.v1.functions.GetFunctionRequest\x1a\x1b.faas.v1.functions.Function\x12b\n" +
	"\rListFunctions\x12'.faas.v1.functions.ListFunctionsRequest\x1a(.faas.v1.functions.ListFunctionsResponse\x12R\n" +
	"\x0eDeleteFunction\x12(.faas.v1.functions.DeleteFunctionRequest\x1a\x16.google.protobuf.EmptyB2Z0github.com/10Narratives/faas/pkg/faas/v1/;faaspbb\x06proto3"

var (
	file_faas_v1_functions_proto_rawDescOnce sync.Once
	file_faas_v1_functions_proto_rawDescData []byte
)

func file_faas_v1_functions_proto_rawDescGZIP() []byte {
	file_faas_v1_functions_proto_rawDescOnce.Do(func() {
		file_faas_v1_functions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_faas_v1_functions_proto_rawDesc), len(file_faas_v1_functions_proto_rawDesc)))
	})
	return file_faas_v1_functions_proto_rawDescData
}

var file_faas_v1_functions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_faas_v1_functions_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_faas_v1_functions_proto_goTypes = []any{
	(UploadFunctionMetadata_Format)(0), // 0: faas.v1.functions.UploadFunctionMetadata.Format
	(*Function)(nil),                   // 1: faas.v1.functions.Function
	(*SourceBundle)(nil),               // 2: faas.v1.functions.SourceBundle
	(*UploadFunctionRequest)(nil),      // 3: faas.v1.functions.UploadFunctionRequest
	(*UploadFunctionMetadata)(nil),     // 4: faas.v1.functions.UploadFunctionMetadata
	(*UploadFunctionData)(nil),         // 5: faas.v1.functions.UploadFunctionData
	(*ExecuteFunctionRequest)(nil),     // 6: faas.v1.functions.ExecuteFunctionRequest
	(*ExecuteFunctionResponse)(nil),    // 7: faas.v1.functions.ExecuteFunctionResponse
	(*GetFunctionRequest)(nil),         // 8: faas.v1.functions.GetFunctionRequest
	(*ListFunctionsRequest)(nil),       // 9: faas.v1.functions.ListFunctionsRequest
	(*ListFunctionsResponse)(nil),      // 10: faas.v1.functions.ListFunctionsResponse
	(*DeleteFunctionRequest)(nil),      // 11: faas.v1.functions.DeleteFunctionRequest
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 13: google.protobuf.Empty
}
var file_faas_v1_functions_proto_depIdxs = []int32{
	12, // 0: faas.v1.functions.Function.uploaded_at:type_name -> google.protobuf.Timestamp
	2,  // 1: faas.v1.functions.Function.source_bundle:type_name -> faas.v1.functions.SourceBundle
	4,  // 2: faas.v1.functions.UploadFunctionRequest.upload_function_metadata:type_name -> faas.v1.functions.UploadFunctionMetadata
	5,  // 3: faas.v1.functions.UploadFunctionRequest.upload_function_data:type_name -> faas.v1.functions.UploadFunctionData
	0,  // 4: faas.v1.functions.UploadFunctionMetadata.format:type_name -> faas.v1.functions.UploadFunctionMetadata.Format
	1,  // 5: faas.v1.functions.ListFunctionsResponse.functions:type_name -> faas.v1.functions.Function
	3,  // 6: faas.v1.functions.Functions.UploadFunction:input_type -> faas.v1.functions.UploadFunctionRequest
	6,  // 7: faas.v1.functions.Functions.ExecuteFunction:input_type -> faas.v1.functions.ExecuteFunctionRequest
	8,  // 8: faas.v1.functions.Functions.GetFunction:input_type -> faas.v1.functions.GetFunctionRequest
	9,  // 9: faas.v1.functions.Functions.ListFunctions:input_type -> faas.v1.functions.ListFunctionsRequest
	11, // 10: faas.v1.functions.Functions.DeleteFunction:input_type -> faas.v1.functions.DeleteFunctionRequest
	1,  // 11: faas.v1.functions.Functions.UploadFunction:output_type -> faas.v1.functions.Function
	7,  // 12: faas.v1.functions.Functions.ExecuteFunction:output_type -> faas.v1.functions.ExecuteFunctionResponse
	1,  // 13: faas.v1.functions.Functions.GetFunction:output_type -> faas.v1.functions.Function
	10, // 14: faas.v1.functions.Functions.ListFunctions:output_type -> faas.v1.functions.ListFunctionsResponse
	13, // 15: faas.v1.functions.Functions.DeleteFunction:output_type -> google.protobuf.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_faas_v1_functions_proto_init() }
func file_faas_v1_functions_proto_init() {
	if File_faas_v1_functions_proto != nil {
		return
	}
	file_faas_v1_functions_proto_msgTypes[2].OneofWrappers = []any{
		(*UploadFunctionRequest_UploadFunctionMetadata)(nil),
		(*UploadFunctionRequest_UploadFunctionData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_faas_v1_functions_proto_rawDesc), len(file_faas_v1_functions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faas_v1_functions_proto_goTypes,
		DependencyIndexes: file_faas_v1_functions_proto_depIdxs,
		EnumInfos:         file_faas_v1_functions_proto_enumTypes,
		MessageInfos:      file_faas_v1_functions_proto_msgTypes,
	}.Build()
	File_faas_v1_functions_proto = out.File
	file_faas_v1_functions_proto_goTypes = nil
	file_faas_v1_functions_proto_depIdxs = nil
}
