// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: faas/v1/functions.proto

package faaspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Functions_UploadFunction_FullMethodName  = "/faas.v1.functions.Functions/UploadFunction"
	Functions_ExecuteFunction_FullMethodName = "/faas.v1.functions.Functions/ExecuteFunction"
	Functions_GetFunction_FullMethodName     = "/faas.v1.functions.Functions/GetFunction"
	Functions_ListFunctions_FullMethodName   = "/faas.v1.functions.Functions/ListFunctions"
	Functions_DeleteFunction_FullMethodName  = "/faas.v1.functions.Functions/DeleteFunction"
)

// FunctionsClient is the client API for Functions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FunctionsClient interface {
	UploadFunction(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFunctionRequest, Function], error)
	ExecuteFunction(ctx context.Context, in *ExecuteFunctionRequest, opts ...grpc.CallOption) (*Task, error)
	GetFunction(ctx context.Context, in *GetFunctionRequest, opts ...grpc.CallOption) (*Function, error)
	ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error)
	DeleteFunction(ctx context.Context, in *DeleteFunctionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type functionsClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionsClient(cc grpc.ClientConnInterface) FunctionsClient {
	return &functionsClient{cc}
}

func (c *functionsClient) UploadFunction(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFunctionRequest, Function], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Functions_ServiceDesc.Streams[0], Functions_UploadFunction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFunctionRequest, Function]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Functions_UploadFunctionClient = grpc.ClientStreamingClient[UploadFunctionRequest, Function]

func (c *functionsClient) ExecuteFunction(ctx context.Context, in *ExecuteFunctionRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, Functions_ExecuteFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionsClient) GetFunction(ctx context.Context, in *GetFunctionRequest, opts ...grpc.CallOption) (*Function, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Function)
	err := c.cc.Invoke(ctx, Functions_GetFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionsClient) ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFunctionsResponse)
	err := c.cc.Invoke(ctx, Functions_ListFunctions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionsClient) DeleteFunction(ctx context.Context, in *DeleteFunctionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Functions_DeleteFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionsServer is the server API for Functions service.
// All implementations must embed UnimplementedFunctionsServer
// for forward compatibility.
type FunctionsServer interface {
	UploadFunction(grpc.ClientStreamingServer[UploadFunctionRequest, Function]) error
	ExecuteFunction(context.Context, *ExecuteFunctionRequest) (*Task, error)
	GetFunction(context.Context, *GetFunctionRequest) (*Function, error)
	ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error)
	DeleteFunction(context.Context, *DeleteFunctionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFunctionsServer()
}

// UnimplementedFunctionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFunctionsServer struct{}

func (UnimplementedFunctionsServer) UploadFunction(grpc.ClientStreamingServer[UploadFunctionRequest, Function]) error {
	return status.Error(codes.Unimplemented, "method UploadFunction not implemented")
}
func (UnimplementedFunctionsServer) ExecuteFunction(context.Context, *ExecuteFunctionRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteFunction not implemented")
}
func (UnimplementedFunctionsServer) GetFunction(context.Context, *GetFunctionRequest) (*Function, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFunction not implemented")
}
func (UnimplementedFunctionsServer) ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFunctions not implemented")
}
func (UnimplementedFunctionsServer) DeleteFunction(context.Context, *DeleteFunctionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFunction not implemented")
}
func (UnimplementedFunctionsServer) mustEmbedUnimplementedFunctionsServer() {}
func (UnimplementedFunctionsServer) testEmbeddedByValue()                   {}

// UnsafeFunctionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunctionsServer will
// result in compilation errors.
type UnsafeFunctionsServer interface {
	mustEmbedUnimplementedFunctionsServer()
}

func RegisterFunctionsServer(s grpc.ServiceRegistrar, srv FunctionsServer) {
	// If the following call panics, it indicates UnimplementedFunctionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Functions_ServiceDesc, srv)
}

func _Functions_UploadFunction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FunctionsServer).UploadFunction(&grpc.GenericServerStream[UploadFunctionRequest, Function]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Functions_UploadFunctionServer = grpc.ClientStreamingServer[UploadFunctionRequest, Function]

func _Functions_ExecuteFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionsServer).ExecuteFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Functions_ExecuteFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionsServer).ExecuteFunction(ctx, req.(*ExecuteFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Functions_GetFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionsServer).GetFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Functions_GetFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionsServer).GetFunction(ctx, req.(*GetFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Functions_ListFunctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFunctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionsServer).ListFunctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Functions_ListFunctions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionsServer).ListFunctions(ctx, req.(*ListFunctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Functions_DeleteFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionsServer).DeleteFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Functions_DeleteFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionsServer).DeleteFunction(ctx, req.(*DeleteFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Functions_ServiceDesc is the grpc.ServiceDesc for Functions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Functions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "faas.v1.functions.Functions",
	HandlerType: (*FunctionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteFunction",
			Handler:    _Functions_ExecuteFunction_Handler,
		},
		{
			MethodName: "GetFunction",
			Handler:    _Functions_GetFunction_Handler,
		},
		{
			MethodName: "ListFunctions",
			Handler:    _Functions_ListFunctions_Handler,
		},
		{
			MethodName: "DeleteFunction",
			Handler:    _Functions_DeleteFunction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFunction",
			Handler:       _Functions_UploadFunction_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "faas/v1/functions.proto",
}
