// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: faas/v1/functions.proto

package faaspb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Function with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Function) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Function with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FunctionMultiError, or nil
// if none found.
func (m *Function) ValidateAll() error {
	return m.validate(true)
}

func (m *Function) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for DisplayName

	if all {
		switch v := interface{}(m.GetUploadedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FunctionValidationError{
					field:  "UploadedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FunctionValidationError{
					field:  "UploadedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUploadedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FunctionValidationError{
				field:  "UploadedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSourceBundle()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FunctionValidationError{
					field:  "SourceBundle",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FunctionValidationError{
					field:  "SourceBundle",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSourceBundle()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FunctionValidationError{
				field:  "SourceBundle",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FunctionMultiError(errors)
	}

	return nil
}

// FunctionMultiError is an error wrapping multiple validation errors returned
// by Function.ValidateAll() if the designated constraints aren't met.
type FunctionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FunctionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FunctionMultiError) AllErrors() []error { return m }

// FunctionValidationError is the validation error returned by
// Function.Validate if the designated constraints aren't met.
type FunctionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FunctionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FunctionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FunctionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FunctionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FunctionValidationError) ErrorName() string { return "FunctionValidationError" }

// Error satisfies the builtin error interface
func (e FunctionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFunction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FunctionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FunctionValidationError{}

// Validate checks the field values on SourceBundle with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SourceBundle) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SourceBundle with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SourceBundleMultiError, or
// nil if none found.
func (m *SourceBundle) ValidateAll() error {
	return m.validate(true)
}

func (m *SourceBundle) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Bucket

	// no validation rules for ObjectKey

	// no validation rules for Size

	// no validation rules for Sha256

	if len(errors) > 0 {
		return SourceBundleMultiError(errors)
	}

	return nil
}

// SourceBundleMultiError is an error wrapping multiple validation errors
// returned by SourceBundle.ValidateAll() if the designated constraints aren't met.
type SourceBundleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SourceBundleMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SourceBundleMultiError) AllErrors() []error { return m }

// SourceBundleValidationError is the validation error returned by
// SourceBundle.Validate if the designated constraints aren't met.
type SourceBundleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SourceBundleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SourceBundleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SourceBundleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SourceBundleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SourceBundleValidationError) ErrorName() string { return "SourceBundleValidationError" }

// Error satisfies the builtin error interface
func (e SourceBundleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSourceBundle.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SourceBundleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SourceBundleValidationError{}

// Validate checks the field values on UploadFunctionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadFunctionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFunctionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFunctionRequestMultiError, or nil if none found.
func (m *UploadFunctionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFunctionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Payload.(type) {
	case *UploadFunctionRequest_UploadFunctionMetadata:
		if v == nil {
			err := UploadFunctionRequestValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetUploadFunctionMetadata()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UploadFunctionRequestValidationError{
						field:  "UploadFunctionMetadata",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UploadFunctionRequestValidationError{
						field:  "UploadFunctionMetadata",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUploadFunctionMetadata()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UploadFunctionRequestValidationError{
					field:  "UploadFunctionMetadata",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *UploadFunctionRequest_UploadFunctionData:
		if v == nil {
			err := UploadFunctionRequestValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetUploadFunctionData()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UploadFunctionRequestValidationError{
						field:  "UploadFunctionData",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UploadFunctionRequestValidationError{
						field:  "UploadFunctionData",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUploadFunctionData()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UploadFunctionRequestValidationError{
					field:  "UploadFunctionData",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return UploadFunctionRequestMultiError(errors)
	}

	return nil
}

// UploadFunctionRequestMultiError is an error wrapping multiple validation
// errors returned by UploadFunctionRequest.ValidateAll() if the designated
// constraints aren't met.
type UploadFunctionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFunctionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFunctionRequestMultiError) AllErrors() []error { return m }

// UploadFunctionRequestValidationError is the validation error returned by
// UploadFunctionRequest.Validate if the designated constraints aren't met.
type UploadFunctionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFunctionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFunctionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFunctionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFunctionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFunctionRequestValidationError) ErrorName() string {
	return "UploadFunctionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadFunctionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFunctionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFunctionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFunctionRequestValidationError{}

// Validate checks the field values on UploadFunctionMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadFunctionMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFunctionMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFunctionMetadataMultiError, or nil if none found.
func (m *UploadFunctionMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFunctionMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FunctionName

	// no validation rules for Format

	if len(errors) > 0 {
		return UploadFunctionMetadataMultiError(errors)
	}

	return nil
}

// UploadFunctionMetadataMultiError is an error wrapping multiple validation
// errors returned by UploadFunctionMetadata.ValidateAll() if the designated
// constraints aren't met.
type UploadFunctionMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFunctionMetadataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFunctionMetadataMultiError) AllErrors() []error { return m }

// UploadFunctionMetadataValidationError is the validation error returned by
// UploadFunctionMetadata.Validate if the designated constraints aren't met.
type UploadFunctionMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFunctionMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFunctionMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFunctionMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFunctionMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFunctionMetadataValidationError) ErrorName() string {
	return "UploadFunctionMetadataValidationError"
}

// Error satisfies the builtin error interface
func (e UploadFunctionMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFunctionMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFunctionMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFunctionMetadataValidationError{}

// Validate checks the field values on UploadFunctionData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadFunctionData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFunctionData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFunctionDataMultiError, or nil if none found.
func (m *UploadFunctionData) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFunctionData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Data

	if len(errors) > 0 {
		return UploadFunctionDataMultiError(errors)
	}

	return nil
}

// UploadFunctionDataMultiError is an error wrapping multiple validation errors
// returned by UploadFunctionData.ValidateAll() if the designated constraints
// aren't met.
type UploadFunctionDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFunctionDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFunctionDataMultiError) AllErrors() []error { return m }

// UploadFunctionDataValidationError is the validation error returned by
// UploadFunctionData.Validate if the designated constraints aren't met.
type UploadFunctionDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFunctionDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFunctionDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFunctionDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFunctionDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFunctionDataValidationError) ErrorName() string {
	return "UploadFunctionDataValidationError"
}

// Error satisfies the builtin error interface
func (e UploadFunctionDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFunctionData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFunctionDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFunctionDataValidationError{}

// Validate checks the field values on ExecuteFunctionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExecuteFunctionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecuteFunctionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecuteFunctionRequestMultiError, or nil if none found.
func (m *ExecuteFunctionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecuteFunctionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Parameters

	if len(errors) > 0 {
		return ExecuteFunctionRequestMultiError(errors)
	}

	return nil
}

// ExecuteFunctionRequestMultiError is an error wrapping multiple validation
// errors returned by ExecuteFunctionRequest.ValidateAll() if the designated
// constraints aren't met.
type ExecuteFunctionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecuteFunctionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecuteFunctionRequestMultiError) AllErrors() []error { return m }

// ExecuteFunctionRequestValidationError is the validation error returned by
// ExecuteFunctionRequest.Validate if the designated constraints aren't met.
type ExecuteFunctionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteFunctionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteFunctionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteFunctionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteFunctionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteFunctionRequestValidationError) ErrorName() string {
	return "ExecuteFunctionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExecuteFunctionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteFunctionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteFunctionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteFunctionRequestValidationError{}

// Validate checks the field values on GetFunctionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetFunctionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFunctionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFunctionRequestMultiError, or nil if none found.
func (m *GetFunctionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFunctionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return GetFunctionRequestMultiError(errors)
	}

	return nil
}

// GetFunctionRequestMultiError is an error wrapping multiple validation errors
// returned by GetFunctionRequest.ValidateAll() if the designated constraints
// aren't met.
type GetFunctionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFunctionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFunctionRequestMultiError) AllErrors() []error { return m }

// GetFunctionRequestValidationError is the validation error returned by
// GetFunctionRequest.Validate if the designated constraints aren't met.
type GetFunctionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFunctionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFunctionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFunctionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFunctionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFunctionRequestValidationError) ErrorName() string {
	return "GetFunctionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetFunctionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFunctionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFunctionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFunctionRequestValidationError{}

// Validate checks the field values on ListFunctionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListFunctionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListFunctionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListFunctionsRequestMultiError, or nil if none found.
func (m *ListFunctionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListFunctionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageSize

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListFunctionsRequestMultiError(errors)
	}

	return nil
}

// ListFunctionsRequestMultiError is an error wrapping multiple validation
// errors returned by ListFunctionsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListFunctionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListFunctionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListFunctionsRequestMultiError) AllErrors() []error { return m }

// ListFunctionsRequestValidationError is the validation error returned by
// ListFunctionsRequest.Validate if the designated constraints aren't met.
type ListFunctionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListFunctionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListFunctionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListFunctionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListFunctionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListFunctionsRequestValidationError) ErrorName() string {
	return "ListFunctionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListFunctionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListFunctionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListFunctionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListFunctionsRequestValidationError{}

// Validate checks the field values on ListFunctionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListFunctionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListFunctionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListFunctionsResponseMultiError, or nil if none found.
func (m *ListFunctionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListFunctionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetFunctions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListFunctionsResponseValidationError{
						field:  fmt.Sprintf("Functions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListFunctionsResponseValidationError{
						field:  fmt.Sprintf("Functions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListFunctionsResponseValidationError{
					field:  fmt.Sprintf("Functions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListFunctionsResponseMultiError(errors)
	}

	return nil
}

// ListFunctionsResponseMultiError is an error wrapping multiple validation
// errors returned by ListFunctionsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListFunctionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListFunctionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListFunctionsResponseMultiError) AllErrors() []error { return m }

// ListFunctionsResponseValidationError is the validation error returned by
// ListFunctionsResponse.Validate if the designated constraints aren't met.
type ListFunctionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListFunctionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListFunctionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListFunctionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListFunctionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListFunctionsResponseValidationError) ErrorName() string {
	return "ListFunctionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListFunctionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListFunctionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListFunctionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListFunctionsResponseValidationError{}

// Validate checks the field values on DeleteFunctionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteFunctionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteFunctionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteFunctionRequestMultiError, or nil if none found.
func (m *DeleteFunctionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteFunctionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return DeleteFunctionRequestMultiError(errors)
	}

	return nil
}

// DeleteFunctionRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteFunctionRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteFunctionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteFunctionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteFunctionRequestMultiError) AllErrors() []error { return m }

// DeleteFunctionRequestValidationError is the validation error returned by
// DeleteFunctionRequest.Validate if the designated constraints aren't met.
type DeleteFunctionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteFunctionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteFunctionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteFunctionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteFunctionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteFunctionRequestValidationError) ErrorName() string {
	return "DeleteFunctionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteFunctionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteFunctionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteFunctionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteFunctionRequestValidationError{}
