// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: faas/v1/tasks.proto

package faaspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_PROCESSING  TaskState = 2
	TaskState_TASK_STATE_SUCCEEDED   TaskState = 3
	TaskState_TASK_STATE_FAILED      TaskState = 4
	TaskState_TASK_STATE_CANCELED    TaskState = 5
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_PROCESSING",
		3: "TASK_STATE_SUCCEEDED",
		4: "TASK_STATE_FAILED",
		5: "TASK_STATE_CANCELED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_PROCESSING":  2,
		"TASK_STATE_SUCCEEDED":   3,
		"TASK_STATE_FAILED":      4,
		"TASK_STATE_CANCELED":    5,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_faas_v1_tasks_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_faas_v1_tasks_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_faas_v1_tasks_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Function   string                 `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	Parameters string                 `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	State      TaskState              `protobuf:"varint,4,opt,name=state,proto3,enum=faas.v1.TaskState" json:"state,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*Task_InlineResult
	//	*Task_ObjectKey
	Result        isTask_Result `protobuf_oneof:"result"`
	ErrorMessage  string        `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_faas_v1_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_faas_v1_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *Task) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Task) GetResult() isTask_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Task) GetInlineResult() []byte {
	if x != nil {
		if x, ok := x.Result.(*Task_InlineResult); ok {
			return x.InlineResult
		}
	}
	return nil
}

func (x *Task) GetObjectKey() string {
	if x != nil {
		if x, ok := x.Result.(*Task_ObjectKey); ok {
			return x.ObjectKey
		}
	}
	return ""
}

func (x *Task) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type isTask_Result interface {
	isTask_Result()
}

type Task_InlineResult struct {
	InlineResult []byte `protobuf:"bytes,10,opt,name=inline_result,json=inlineResult,proto3,oneof"`
}

type Task_ObjectKey struct {
	ObjectKey string `protobuf:"bytes,11,opt,name=object_key,json=objectKey,proto3,oneof"`
}

func (*Task_InlineResult) isTask_Result() {}

func (*Task_ObjectKey) isTask_Result() {}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_faas_v1_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_tasks_proto_rawDescGZIP(), []int{1}
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_faas_v1_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_faas_v1_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_faas_v1_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_faas_v1_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_tasks_proto_rawDescGZIP(), []int{4}
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_faas_v1_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_tasks_proto_rawDescGZIP(), []int{5}
}

var File_faas_v1_tasks_proto protoreflect.FileDescriptor

const file_faas_v1_tasks_proto_rawDesc = "" +
	"\n" +
	"\x13faas/v1/tasks.proto\x12\afaas.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x03\n" +
	"\x04Task\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bfunction\x18\x02 \x01(\tR\bfunction\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parameters\x12(\n" +
	"\x05state\x18\x04 \x01(\x0e2\x12.faas.v1.TaskStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12%\n" +
	"\rinline_result\x18\n" +
	" \x01(\fH\x00R\finlineResult\x12\x1f\n" +
	"\n" +
	"object_key\x18\v \x01(\tH\x00R\tobjectKey\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessageB\b\n" +
	"\x06result\"\x10\n" +
	"\x0eGetTaskRequest\"N\n" +
	"\x10ListTasksRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"`\n" +
	"\x11ListTasksResponse\x12#\n" +
	"\x05tasks\x18\x01 \x03(\v2\r.faas.v1.TaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x13\n" +
	"\x11DeleteTaskRequest\"\x13\n" +
	"\x11CancelTaskRequest*\xa4\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x19\n" +
	"\x15TASK_STATE_PROCESSING\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x04\x12\x17\n" +
	"\x13TASK_STATE_CANCELED\x10\x052\xf9\x01\n" +
	"\x05Tasks\x121\n" +
	"\aGetTask\x12\x17.faas.v1.GetTaskRequest\x1a\r.faas.v1.Task\x12B\n" +
	"\tListTasks\x12\x19.faas.v1.ListTasksRequest\x1a\x1a.faas.v1.ListTasksResponse\x12@\n" +
	"\n" +
	"DeleteTask\x12\x1a.faas.v1.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\n" +
	"CancelTask\x12\x1a.faas.v1.CancelTaskRequest\x1a\r.faas.v1.TaskB2Z0github.com/10Narratives/faas/pkg/faas/v1/;faaspbb\x06proto3"

var (
	file_faas_v1_tasks_proto_rawDescOnce sync.Once
	file_faas_v1_tasks_proto_rawDescData []byte
)

func file_faas_v1_tasks_proto_rawDescGZIP() []byte {
	file_faas_v1_tasks_proto_rawDescOnce.Do(func() {
		file_faas_v1_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_faas_v1_tasks_proto_rawDesc), len(file_faas_v1_tasks_proto_rawDesc)))
	})
	return file_faas_v1_tasks_proto_rawDescData
}

var file_faas_v1_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_faas_v1_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_faas_v1_tasks_proto_goTypes = []any{
	(TaskState)(0),                // 0: faas.v1.TaskState
	(*Task)(nil),                  // 1: faas.v1.Task
	(*GetTaskRequest)(nil),        // 2: faas.v1.GetTaskRequest
	(*ListTasksRequest)(nil),      // 3: faas.v1.ListTasksRequest
	(*ListTasksResponse)(nil),     // 4: faas.v1.ListTasksResponse
	(*DeleteTaskRequest)(nil),     // 5: faas.v1.DeleteTaskRequest
	(*CancelTaskRequest)(nil),     // 6: faas.v1.CancelTaskRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_faas_v1_tasks_proto_depIdxs = []int32{
	0, // 0: faas.v1.Task.state:type_name -> faas.v1.TaskState
	7, // 1: faas.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	7, // 2: faas.v1.Task.started_at:type_name -> google.protobuf.Timestamp
	7, // 3: faas.v1.Task.ended_at:type_name -> google.protobuf.Timestamp
	1, // 4: faas.v1.ListTasksResponse.tasks:type_name -> faas.v1.Task
	2, // 5: faas.v1.Tasks.GetTask:input_type -> faas.v1.GetTaskRequest
	3, // 6: faas.v1.Tasks.ListTasks:input_type -> faas.v1.ListTasksRequest
	5, // 7: faas.v1.Tasks.DeleteTask:input_type -> faas.v1.DeleteTaskRequest
	6, // 8: faas.v1.Tasks.CancelTask:input_type -> faas.v1.CancelTaskRequest
	1, // 9: faas.v1.Tasks.GetTask:output_type -> faas.v1.Task
	4, // 10: faas.v1.Tasks.ListTasks:output_type -> faas.v1.ListTasksResponse
	8, // 11: faas.v1.Tasks.DeleteTask:output_type -> google.protobuf.Empty
	1, // 12: faas.v1.Tasks.CancelTask:output_type -> faas.v1.Task
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_faas_v1_tasks_proto_init() }
func file_faas_v1_tasks_proto_init() {
	if File_faas_v1_tasks_proto != nil {
		return
	}
	file_faas_v1_tasks_proto_msgTypes[0].OneofWrappers = []any{
		(*Task_InlineResult)(nil),
		(*Task_ObjectKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_faas_v1_tasks_proto_rawDesc), len(file_faas_v1_tasks_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faas_v1_tasks_proto_goTypes,
		DependencyIndexes: file_faas_v1_tasks_proto_depIdxs,
		EnumInfos:         file_faas_v1_tasks_proto_enumTypes,
		MessageInfos:      file_faas_v1_tasks_proto_msgTypes,
	}.Build()
	File_faas_v1_tasks_proto = out.File
	file_faas_v1_tasks_proto_goTypes = nil
	file_faas_v1_tasks_proto_depIdxs = nil
}
