// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: faas/functions/v1/function_service.proto

package functionspb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UploadFunctionSourceRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadFunctionSourceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFunctionSourceRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFunctionSourceRequestMultiError, or nil if none found.
func (m *UploadFunctionSourceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFunctionSourceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Payload.(type) {
	case *UploadFunctionSourceRequest_Metadata:
		if v == nil {
			err := UploadFunctionSourceRequestValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetMetadata()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UploadFunctionSourceRequestValidationError{
						field:  "Metadata",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UploadFunctionSourceRequestValidationError{
						field:  "Metadata",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UploadFunctionSourceRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *UploadFunctionSourceRequest_Chunk:
		if v == nil {
			err := UploadFunctionSourceRequestValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetChunk()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UploadFunctionSourceRequestValidationError{
						field:  "Chunk",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UploadFunctionSourceRequestValidationError{
						field:  "Chunk",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetChunk()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UploadFunctionSourceRequestValidationError{
					field:  "Chunk",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return UploadFunctionSourceRequestMultiError(errors)
	}

	return nil
}

// UploadFunctionSourceRequestMultiError is an error wrapping multiple
// validation errors returned by UploadFunctionSourceRequest.ValidateAll() if
// the designated constraints aren't met.
type UploadFunctionSourceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFunctionSourceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFunctionSourceRequestMultiError) AllErrors() []error { return m }

// UploadFunctionSourceRequestValidationError is the validation error returned
// by UploadFunctionSourceRequest.Validate if the designated constraints
// aren't met.
type UploadFunctionSourceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFunctionSourceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFunctionSourceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFunctionSourceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFunctionSourceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFunctionSourceRequestValidationError) ErrorName() string {
	return "UploadFunctionSourceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadFunctionSourceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFunctionSourceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFunctionSourceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFunctionSourceRequestValidationError{}

// Validate checks the field values on UploadFunctionSourceMetadata with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadFunctionSourceMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFunctionSourceMetadata with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFunctionSourceMetadataMultiError, or nil if none found.
func (m *UploadFunctionSourceMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFunctionSourceMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FunctionName

	if all {
		switch v := interface{}(m.GetSourceBundleMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UploadFunctionSourceMetadataValidationError{
					field:  "SourceBundleMetadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UploadFunctionSourceMetadataValidationError{
					field:  "SourceBundleMetadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSourceBundleMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UploadFunctionSourceMetadataValidationError{
				field:  "SourceBundleMetadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UploadFunctionSourceMetadataMultiError(errors)
	}

	return nil
}

// UploadFunctionSourceMetadataMultiError is an error wrapping multiple
// validation errors returned by UploadFunctionSourceMetadata.ValidateAll() if
// the designated constraints aren't met.
type UploadFunctionSourceMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFunctionSourceMetadataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFunctionSourceMetadataMultiError) AllErrors() []error { return m }

// UploadFunctionSourceMetadataValidationError is the validation error returned
// by UploadFunctionSourceMetadata.Validate if the designated constraints
// aren't met.
type UploadFunctionSourceMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFunctionSourceMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFunctionSourceMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFunctionSourceMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFunctionSourceMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFunctionSourceMetadataValidationError) ErrorName() string {
	return "UploadFunctionSourceMetadataValidationError"
}

// Error satisfies the builtin error interface
func (e UploadFunctionSourceMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFunctionSourceMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFunctionSourceMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFunctionSourceMetadataValidationError{}

// Validate checks the field values on SourceBundleMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SourceBundleMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SourceBundleMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SourceBundleMetadataMultiError, or nil if none found.
func (m *SourceBundleMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *SourceBundleMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for FileName

	// no validation rules for SizeBytes

	if len(errors) > 0 {
		return SourceBundleMetadataMultiError(errors)
	}

	return nil
}

// SourceBundleMetadataMultiError is an error wrapping multiple validation
// errors returned by SourceBundleMetadata.ValidateAll() if the designated
// constraints aren't met.
type SourceBundleMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SourceBundleMetadataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SourceBundleMetadataMultiError) AllErrors() []error { return m }

// SourceBundleMetadataValidationError is the validation error returned by
// SourceBundleMetadata.Validate if the designated constraints aren't met.
type SourceBundleMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SourceBundleMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SourceBundleMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SourceBundleMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SourceBundleMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SourceBundleMetadataValidationError) ErrorName() string {
	return "SourceBundleMetadataValidationError"
}

// Error satisfies the builtin error interface
func (e SourceBundleMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSourceBundleMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SourceBundleMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SourceBundleMetadataValidationError{}

// Validate checks the field values on UploadChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UploadChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UploadChunkMultiError, or
// nil if none found.
func (m *UploadChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Data

	if len(errors) > 0 {
		return UploadChunkMultiError(errors)
	}

	return nil
}

// UploadChunkMultiError is an error wrapping multiple validation errors
// returned by UploadChunk.ValidateAll() if the designated constraints aren't met.
type UploadChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadChunkMultiError) AllErrors() []error { return m }

// UploadChunkValidationError is the validation error returned by
// UploadChunk.Validate if the designated constraints aren't met.
type UploadChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadChunkValidationError) ErrorName() string { return "UploadChunkValidationError" }

// Error satisfies the builtin error interface
func (e UploadChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadChunkValidationError{}

// Validate checks the field values on UploadFunctionSourceResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadFunctionSourceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFunctionSourceResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFunctionSourceResponseMultiError, or nil if none found.
func (m *UploadFunctionSourceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFunctionSourceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FunctionId

	// no validation rules for ObjectKey

	if len(errors) > 0 {
		return UploadFunctionSourceResponseMultiError(errors)
	}

	return nil
}

// UploadFunctionSourceResponseMultiError is an error wrapping multiple
// validation errors returned by UploadFunctionSourceResponse.ValidateAll() if
// the designated constraints aren't met.
type UploadFunctionSourceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFunctionSourceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFunctionSourceResponseMultiError) AllErrors() []error { return m }

// UploadFunctionSourceResponseValidationError is the validation error returned
// by UploadFunctionSourceResponse.Validate if the designated constraints
// aren't met.
type UploadFunctionSourceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFunctionSourceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFunctionSourceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFunctionSourceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFunctionSourceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFunctionSourceResponseValidationError) ErrorName() string {
	return "UploadFunctionSourceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UploadFunctionSourceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFunctionSourceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFunctionSourceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFunctionSourceResponseValidationError{}
