// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: faas/functions/v1/function_service.proto

package functionspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FunctionService_UploadFunctionSource_FullMethodName = "/faas.functions.v1.FunctionService/UploadFunctionSource"
)

// FunctionServiceClient is the client API for FunctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FunctionServiceClient interface {
	UploadFunctionSource(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFunctionSourceRequest, UploadFunctionSourceResponse], error)
}

type functionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionServiceClient(cc grpc.ClientConnInterface) FunctionServiceClient {
	return &functionServiceClient{cc}
}

func (c *functionServiceClient) UploadFunctionSource(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFunctionSourceRequest, UploadFunctionSourceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FunctionService_ServiceDesc.Streams[0], FunctionService_UploadFunctionSource_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFunctionSourceRequest, UploadFunctionSourceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FunctionService_UploadFunctionSourceClient = grpc.ClientStreamingClient[UploadFunctionSourceRequest, UploadFunctionSourceResponse]

// FunctionServiceServer is the server API for FunctionService service.
// All implementations must embed UnimplementedFunctionServiceServer
// for forward compatibility.
type FunctionServiceServer interface {
	UploadFunctionSource(grpc.ClientStreamingServer[UploadFunctionSourceRequest, UploadFunctionSourceResponse]) error
	mustEmbedUnimplementedFunctionServiceServer()
}

// UnimplementedFunctionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFunctionServiceServer struct{}

func (UnimplementedFunctionServiceServer) UploadFunctionSource(grpc.ClientStreamingServer[UploadFunctionSourceRequest, UploadFunctionSourceResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadFunctionSource not implemented")
}
func (UnimplementedFunctionServiceServer) mustEmbedUnimplementedFunctionServiceServer() {}
func (UnimplementedFunctionServiceServer) testEmbeddedByValue()                         {}

// UnsafeFunctionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunctionServiceServer will
// result in compilation errors.
type UnsafeFunctionServiceServer interface {
	mustEmbedUnimplementedFunctionServiceServer()
}

func RegisterFunctionServiceServer(s grpc.ServiceRegistrar, srv FunctionServiceServer) {
	// If the following call panics, it indicates UnimplementedFunctionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FunctionService_ServiceDesc, srv)
}

func _FunctionService_UploadFunctionSource_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FunctionServiceServer).UploadFunctionSource(&grpc.GenericServerStream[UploadFunctionSourceRequest, UploadFunctionSourceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FunctionService_UploadFunctionSourceServer = grpc.ClientStreamingServer[UploadFunctionSourceRequest, UploadFunctionSourceResponse]

// FunctionService_ServiceDesc is the grpc.ServiceDesc for FunctionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FunctionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "faas.functions.v1.FunctionService",
	HandlerType: (*FunctionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFunctionSource",
			Handler:       _FunctionService_UploadFunctionSource_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "faas/functions/v1/function_service.proto",
}
