// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	taskdomain "github.com/10Narratives/faas/internal/domains/tasks"
	mock "github.com/stretchr/testify/mock"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

type TaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskRepository) EXPECT() *TaskRepository_Expecter {
	return &TaskRepository_Expecter{mock: &_m.Mock}
}

// CancelTask provides a mock function with given fields: ctx, args
func (_m *TaskRepository) CancelTask(ctx context.Context, args *taskdomain.CancelTaskArgs) (*taskdomain.CancelTaskResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CancelTask")
	}

	var r0 *taskdomain.CancelTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.CancelTaskArgs) (*taskdomain.CancelTaskResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.CancelTaskArgs) *taskdomain.CancelTaskResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskdomain.CancelTaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *taskdomain.CancelTaskArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_CancelTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTask'
type TaskRepository_CancelTask_Call struct {
	*mock.Call
}

// CancelTask is a helper method to define mock.On call
//   - ctx context.Context
//   - args *taskdomain.CancelTaskArgs
func (_e *TaskRepository_Expecter) CancelTask(ctx interface{}, args interface{}) *TaskRepository_CancelTask_Call {
	return &TaskRepository_CancelTask_Call{Call: _e.mock.On("CancelTask", ctx, args)}
}

func (_c *TaskRepository_CancelTask_Call) Run(run func(ctx context.Context, args *taskdomain.CancelTaskArgs)) *TaskRepository_CancelTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.CancelTaskArgs))
	})
	return _c
}

func (_c *TaskRepository_CancelTask_Call) Return(_a0 *taskdomain.CancelTaskResult, _a1 error) *TaskRepository_CancelTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_CancelTask_Call) RunAndReturn(run func(context.Context, *taskdomain.CancelTaskArgs) (*taskdomain.CancelTaskResult, error)) *TaskRepository_CancelTask_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: ctx, args
func (_m *TaskRepository) CreateTask(ctx context.Context, args *taskdomain.CreateTaskArgs) (*taskdomain.CreateTaskResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *taskdomain.CreateTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.CreateTaskArgs) (*taskdomain.CreateTaskResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.CreateTaskArgs) *taskdomain.CreateTaskResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskdomain.CreateTaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *taskdomain.CreateTaskArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type TaskRepository_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - args *taskdomain.CreateTaskArgs
func (_e *TaskRepository_Expecter) CreateTask(ctx interface{}, args interface{}) *TaskRepository_CreateTask_Call {
	return &TaskRepository_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, args)}
}

func (_c *TaskRepository_CreateTask_Call) Run(run func(ctx context.Context, args *taskdomain.CreateTaskArgs)) *TaskRepository_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.CreateTaskArgs))
	})
	return _c
}

func (_c *TaskRepository_CreateTask_Call) Return(_a0 *taskdomain.CreateTaskResult, _a1 error) *TaskRepository_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_CreateTask_Call) RunAndReturn(run func(context.Context, *taskdomain.CreateTaskArgs) (*taskdomain.CreateTaskResult, error)) *TaskRepository_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: ctx, args
func (_m *TaskRepository) DeleteTask(ctx context.Context, args *taskdomain.DeleteTaskArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.DeleteTaskArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskRepository_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type TaskRepository_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - args *taskdomain.DeleteTaskArgs
func (_e *TaskRepository_Expecter) DeleteTask(ctx interface{}, args interface{}) *TaskRepository_DeleteTask_Call {
	return &TaskRepository_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, args)}
}

func (_c *TaskRepository_DeleteTask_Call) Run(run func(ctx context.Context, args *taskdomain.DeleteTaskArgs)) *TaskRepository_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.DeleteTaskArgs))
	})
	return _c
}

func (_c *TaskRepository_DeleteTask_Call) Return(_a0 error) *TaskRepository_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskRepository_DeleteTask_Call) RunAndReturn(run func(context.Context, *taskdomain.DeleteTaskArgs) error) *TaskRepository_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, args
func (_m *TaskRepository) GetTask(ctx context.Context, args *taskdomain.GetTaskArgs) (*taskdomain.GetTaskResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *taskdomain.GetTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.GetTaskArgs) (*taskdomain.GetTaskResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.GetTaskArgs) *taskdomain.GetTaskResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskdomain.GetTaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *taskdomain.GetTaskArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type TaskRepository_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - args *taskdomain.GetTaskArgs
func (_e *TaskRepository_Expecter) GetTask(ctx interface{}, args interface{}) *TaskRepository_GetTask_Call {
	return &TaskRepository_GetTask_Call{Call: _e.mock.On("GetTask", ctx, args)}
}

func (_c *TaskRepository_GetTask_Call) Run(run func(ctx context.Context, args *taskdomain.GetTaskArgs)) *TaskRepository_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.GetTaskArgs))
	})
	return _c
}

func (_c *TaskRepository_GetTask_Call) Return(_a0 *taskdomain.GetTaskResult, _a1 error) *TaskRepository_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_GetTask_Call) RunAndReturn(run func(context.Context, *taskdomain.GetTaskArgs) (*taskdomain.GetTaskResult, error)) *TaskRepository_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx, args
func (_m *TaskRepository) ListTasks(ctx context.Context, args *taskdomain.ListTasksArgs) (*taskdomain.ListTaskResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 *taskdomain.ListTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.ListTasksArgs) (*taskdomain.ListTaskResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.ListTasksArgs) *taskdomain.ListTaskResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskdomain.ListTaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *taskdomain.ListTasksArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type TaskRepository_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - args *taskdomain.ListTasksArgs
func (_e *TaskRepository_Expecter) ListTasks(ctx interface{}, args interface{}) *TaskRepository_ListTasks_Call {
	return &TaskRepository_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, args)}
}

func (_c *TaskRepository_ListTasks_Call) Run(run func(ctx context.Context, args *taskdomain.ListTasksArgs)) *TaskRepository_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.ListTasksArgs))
	})
	return _c
}

func (_c *TaskRepository_ListTasks_Call) Return(_a0 *taskdomain.ListTaskResult, _a1 error) *TaskRepository_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_ListTasks_Call) RunAndReturn(run func(context.Context, *taskdomain.ListTasksArgs) (*taskdomain.ListTaskResult, error)) *TaskRepository_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
