// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	taskdomain "github.com/10Narratives/faas/internal/domains/tasks"
	mock "github.com/stretchr/testify/mock"
)

// TaskPublisher is an autogenerated mock type for the TaskPublisher type
type TaskPublisher struct {
	mock.Mock
}

type TaskPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskPublisher) EXPECT() *TaskPublisher_Expecter {
	return &TaskPublisher_Expecter{mock: &_m.Mock}
}

// PublishCancel provides a mock function with given fields: ctx, msg
func (_m *TaskPublisher) PublishCancel(ctx context.Context, msg *taskdomain.CancelTaskMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for PublishCancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.CancelTaskMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskPublisher_PublishCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCancel'
type TaskPublisher_PublishCancel_Call struct {
	*mock.Call
}

// PublishCancel is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *taskdomain.CancelTaskMessage
func (_e *TaskPublisher_Expecter) PublishCancel(ctx interface{}, msg interface{}) *TaskPublisher_PublishCancel_Call {
	return &TaskPublisher_PublishCancel_Call{Call: _e.mock.On("PublishCancel", ctx, msg)}
}

func (_c *TaskPublisher_PublishCancel_Call) Run(run func(ctx context.Context, msg *taskdomain.CancelTaskMessage)) *TaskPublisher_PublishCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.CancelTaskMessage))
	})
	return _c
}

func (_c *TaskPublisher_PublishCancel_Call) Return(_a0 error) *TaskPublisher_PublishCancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskPublisher_PublishCancel_Call) RunAndReturn(run func(context.Context, *taskdomain.CancelTaskMessage) error) *TaskPublisher_PublishCancel_Call {
	_c.Call.Return(run)
	return _c
}

// PublishExecute provides a mock function with given fields: ctx, msg
func (_m *TaskPublisher) PublishExecute(ctx context.Context, msg *taskdomain.ExecuteTaskMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for PublishExecute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *taskdomain.ExecuteTaskMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskPublisher_PublishExecute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishExecute'
type TaskPublisher_PublishExecute_Call struct {
	*mock.Call
}

// PublishExecute is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *taskdomain.ExecuteTaskMessage
func (_e *TaskPublisher_Expecter) PublishExecute(ctx interface{}, msg interface{}) *TaskPublisher_PublishExecute_Call {
	return &TaskPublisher_PublishExecute_Call{Call: _e.mock.On("PublishExecute", ctx, msg)}
}

func (_c *TaskPublisher_PublishExecute_Call) Run(run func(ctx context.Context, msg *taskdomain.ExecuteTaskMessage)) *TaskPublisher_PublishExecute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*taskdomain.ExecuteTaskMessage))
	})
	return _c
}

func (_c *TaskPublisher_PublishExecute_Call) Return(_a0 error) *TaskPublisher_PublishExecute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskPublisher_PublishExecute_Call) RunAndReturn(run func(context.Context, *taskdomain.ExecuteTaskMessage) error) *TaskPublisher_PublishExecute_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskPublisher creates a new instance of TaskPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskPublisher {
	mock := &TaskPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
