// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	funcdomain "github.com/10Narratives/faas/internal/domains/functions"

	mock "github.com/stretchr/testify/mock"
)

// FunctionService is an autogenerated mock type for the FunctionService type
type FunctionService struct {
	mock.Mock
}

type FunctionService_Expecter struct {
	mock *mock.Mock
}

func (_m *FunctionService) EXPECT() *FunctionService_Expecter {
	return &FunctionService_Expecter{mock: &_m.Mock}
}

// DeleteFunction provides a mock function with given fields: ctx, args
func (_m *FunctionService) DeleteFunction(ctx context.Context, args *funcdomain.DeleteFunctionArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFunction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *funcdomain.DeleteFunctionArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FunctionService_DeleteFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFunction'
type FunctionService_DeleteFunction_Call struct {
	*mock.Call
}

// DeleteFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - args *funcdomain.DeleteFunctionArgs
func (_e *FunctionService_Expecter) DeleteFunction(ctx interface{}, args interface{}) *FunctionService_DeleteFunction_Call {
	return &FunctionService_DeleteFunction_Call{Call: _e.mock.On("DeleteFunction", ctx, args)}
}

func (_c *FunctionService_DeleteFunction_Call) Run(run func(ctx context.Context, args *funcdomain.DeleteFunctionArgs)) *FunctionService_DeleteFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*funcdomain.DeleteFunctionArgs))
	})
	return _c
}

func (_c *FunctionService_DeleteFunction_Call) Return(_a0 error) *FunctionService_DeleteFunction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FunctionService_DeleteFunction_Call) RunAndReturn(run func(context.Context, *funcdomain.DeleteFunctionArgs) error) *FunctionService_DeleteFunction_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteFunction provides a mock function with given fields: ctx, args
func (_m *FunctionService) ExecuteFunction(ctx context.Context, args *funcdomain.ExecuteFunctionArgs) (*funcdomain.ExecuteFunctionResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteFunction")
	}

	var r0 *funcdomain.ExecuteFunctionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *funcdomain.ExecuteFunctionArgs) (*funcdomain.ExecuteFunctionResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *funcdomain.ExecuteFunctionArgs) *funcdomain.ExecuteFunctionResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*funcdomain.ExecuteFunctionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *funcdomain.ExecuteFunctionArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FunctionService_ExecuteFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteFunction'
type FunctionService_ExecuteFunction_Call struct {
	*mock.Call
}

// ExecuteFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - args *funcdomain.ExecuteFunctionArgs
func (_e *FunctionService_Expecter) ExecuteFunction(ctx interface{}, args interface{}) *FunctionService_ExecuteFunction_Call {
	return &FunctionService_ExecuteFunction_Call{Call: _e.mock.On("ExecuteFunction", ctx, args)}
}

func (_c *FunctionService_ExecuteFunction_Call) Run(run func(ctx context.Context, args *funcdomain.ExecuteFunctionArgs)) *FunctionService_ExecuteFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*funcdomain.ExecuteFunctionArgs))
	})
	return _c
}

func (_c *FunctionService_ExecuteFunction_Call) Return(_a0 *funcdomain.ExecuteFunctionResult, _a1 error) *FunctionService_ExecuteFunction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FunctionService_ExecuteFunction_Call) RunAndReturn(run func(context.Context, *funcdomain.ExecuteFunctionArgs) (*funcdomain.ExecuteFunctionResult, error)) *FunctionService_ExecuteFunction_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunction provides a mock function with given fields: ctx, args
func (_m *FunctionService) GetFunction(ctx context.Context, args *funcdomain.GetFunctionArgs) (*funcdomain.GetFunctionResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetFunction")
	}

	var r0 *funcdomain.GetFunctionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *funcdomain.GetFunctionArgs) (*funcdomain.GetFunctionResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *funcdomain.GetFunctionArgs) *funcdomain.GetFunctionResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*funcdomain.GetFunctionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *funcdomain.GetFunctionArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FunctionService_GetFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunction'
type FunctionService_GetFunction_Call struct {
	*mock.Call
}

// GetFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - args *funcdomain.GetFunctionArgs
func (_e *FunctionService_Expecter) GetFunction(ctx interface{}, args interface{}) *FunctionService_GetFunction_Call {
	return &FunctionService_GetFunction_Call{Call: _e.mock.On("GetFunction", ctx, args)}
}

func (_c *FunctionService_GetFunction_Call) Run(run func(ctx context.Context, args *funcdomain.GetFunctionArgs)) *FunctionService_GetFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*funcdomain.GetFunctionArgs))
	})
	return _c
}

func (_c *FunctionService_GetFunction_Call) Return(_a0 *funcdomain.GetFunctionResult, _a1 error) *FunctionService_GetFunction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FunctionService_GetFunction_Call) RunAndReturn(run func(context.Context, *funcdomain.GetFunctionArgs) (*funcdomain.GetFunctionResult, error)) *FunctionService_GetFunction_Call {
	_c.Call.Return(run)
	return _c
}

// ListFunctions provides a mock function with given fields: ctx, args
func (_m *FunctionService) ListFunctions(ctx context.Context, args *funcdomain.ListFunctionsArgs) (*funcdomain.ListFunctionsResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListFunctions")
	}

	var r0 *funcdomain.ListFunctionsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *funcdomain.ListFunctionsArgs) (*funcdomain.ListFunctionsResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *funcdomain.ListFunctionsArgs) *funcdomain.ListFunctionsResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*funcdomain.ListFunctionsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *funcdomain.ListFunctionsArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FunctionService_ListFunctions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFunctions'
type FunctionService_ListFunctions_Call struct {
	*mock.Call
}

// ListFunctions is a helper method to define mock.On call
//   - ctx context.Context
//   - args *funcdomain.ListFunctionsArgs
func (_e *FunctionService_Expecter) ListFunctions(ctx interface{}, args interface{}) *FunctionService_ListFunctions_Call {
	return &FunctionService_ListFunctions_Call{Call: _e.mock.On("ListFunctions", ctx, args)}
}

func (_c *FunctionService_ListFunctions_Call) Run(run func(ctx context.Context, args *funcdomain.ListFunctionsArgs)) *FunctionService_ListFunctions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*funcdomain.ListFunctionsArgs))
	})
	return _c
}

func (_c *FunctionService_ListFunctions_Call) Return(_a0 *funcdomain.ListFunctionsResult, _a1 error) *FunctionService_ListFunctions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FunctionService_ListFunctions_Call) RunAndReturn(run func(context.Context, *funcdomain.ListFunctionsArgs) (*funcdomain.ListFunctionsResult, error)) *FunctionService_ListFunctions_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFunction provides a mock function with given fields: ctx, args
func (_m *FunctionService) UploadFunction(ctx context.Context, args *funcdomain.UploadFunctionArgs) (*funcdomain.UploadFunctionResult, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for UploadFunction")
	}

	var r0 *funcdomain.UploadFunctionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *funcdomain.UploadFunctionArgs) (*funcdomain.UploadFunctionResult, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *funcdomain.UploadFunctionArgs) *funcdomain.UploadFunctionResult); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*funcdomain.UploadFunctionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *funcdomain.UploadFunctionArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FunctionService_UploadFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFunction'
type FunctionService_UploadFunction_Call struct {
	*mock.Call
}

// UploadFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - args *funcdomain.UploadFunctionArgs
func (_e *FunctionService_Expecter) UploadFunction(ctx interface{}, args interface{}) *FunctionService_UploadFunction_Call {
	return &FunctionService_UploadFunction_Call{Call: _e.mock.On("UploadFunction", ctx, args)}
}

func (_c *FunctionService_UploadFunction_Call) Run(run func(ctx context.Context, args *funcdomain.UploadFunctionArgs)) *FunctionService_UploadFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*funcdomain.UploadFunctionArgs))
	})
	return _c
}

func (_c *FunctionService_UploadFunction_Call) Return(_a0 *funcdomain.UploadFunctionResult, _a1 error) *FunctionService_UploadFunction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FunctionService_UploadFunction_Call) RunAndReturn(run func(context.Context, *funcdomain.UploadFunctionArgs) (*funcdomain.UploadFunctionResult, error)) *FunctionService_UploadFunction_Call {
	_c.Call.Return(run)
	return _c
}

// NewFunctionService creates a new instance of FunctionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFunctionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FunctionService {
	mock := &FunctionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
